// models/DiscountCode.js
const mongoose = require("mongoose");

const DiscountCodeSchema = new mongoose.Schema(
  {
    code: {
      type: String,
      required: true,
      unique: true,
      uppercase: true,
      trim: true,
    },
    description: {
      type: String,
      required: true,
      trim: true,
    },
    type: {
      type: String,
      enum: ["percent", "fixed"],
      required: true,
    },
    value: {
      type: Number,
      required: true,
      min: 0,
    },
    startDate: {
      type: Date,
      required: true,
    },
    endDate: {
      type: Date,
      required: true,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
    maxUses: {
      type: Number,
      min: 0,
    },
    usesCount: {
      type: Number,
      default: 0,
      min: 0,
    },
    maxUsesPerUser: {
      type: Number,
      min: 0,
    },
    minOrderValue: {
      type: Number,
      min: 0,
      default: 0,
    },
    maxDiscountAmount: {
      type: Number,
      min: 0,
    },
    // Eligibility rules
    books: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Book",
      },
    ],
    categories: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: "Category",
      },
    ],
    // Auto-generation settings
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    prefix: {
      type: String,
      trim: true,
    },
    // User tracking
    usedBy: [
      {
        user: { type: mongoose.Schema.Types.ObjectId, ref: "Account" },
        usedAt: { type: Date, default: Date.now },
        orderValue: { type: Number },
        discountApplied: { type: Number },
      },
    ],
    // Admin tracking
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Account",
    },
    lastModifiedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Account",
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Virtual fields
DiscountCodeSchema.virtual("isExpired").get(function () {
  return new Date() > this.endDate;
});

DiscountCodeSchema.virtual("isNotYetActive").get(function () {
  return new Date() < this.startDate;
});

DiscountCodeSchema.virtual("isValidNow").get(function () {
  const now = new Date();
  return this.isActive && now >= this.startDate && now <= this.endDate;
});

DiscountCodeSchema.virtual("remainingUses").get(function () {
  if (!this.maxUses) return null;
  return Math.max(0, this.maxUses - this.usesCount);
});

DiscountCodeSchema.virtual("usageRate").get(function () {
  if (!this.maxUses) return 0;
  return (this.usesCount / this.maxUses) * 100;
});

// Indexes for performance
DiscountCodeSchema.index({ code: 1 });
DiscountCodeSchema.index({ isActive: 1, startDate: 1, endDate: 1 });
DiscountCodeSchema.index({ createdAt: -1 });
DiscountCodeSchema.index({ categories: 1 });
DiscountCodeSchema.index({ books: 1 });

// Pre-save middleware
DiscountCodeSchema.pre("save", function (next) {
  if (this.isModified("code")) {
    this.code = this.code.toUpperCase();
  }
  next();
});

module.exports = mongoose.model("DiscountCode", DiscountCodeSchema);
